[package]

name = "drophash_rs"
version = "0.0.1"
authors = [ "Your name <you@example.com>" ]
build="build.rs"

[dependencies]

libc = "0.2.11"
winapi = "0.2.7"
user32-sys = "0.2.0"
kernel32-sys = "0.2.2"
gdi32-sys = "0.2.0" 
shell32-sys = "0.1.1"